// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetrotechEmporium.Data;

#nullable disable

namespace RetrotechEmporium.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624003127_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetrotechEmporium.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Retro Gaming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Retro Computers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Modern Tech"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Retro Tech"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Modern Computers"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Modern Gaming"
                        });
                });

            modelBuilder.Entity("RetrotechEmporium.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("productPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("yearReleased")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            categoryId = 1,
                            productDescription = "Classic 8-bit gaming console",
                            productImage = "/images/nes.jpg",
                            productName = "Nintendo Entertainment System",
                            productPrice = 99.99m,
                            quantityInStock = 5,
                            yearReleased = 1985
                        },
                        new
                        {
                            productId = 2,
                            categoryId = 2,
                            productDescription = "Iconic home computer of the 80s",
                            productImage = "/images/c64.jpg",
                            productName = "Commodore 64",
                            productPrice = 149.99m,
                            quantityInStock = 3,
                            yearReleased = 1982
                        });
                });

            modelBuilder.Entity("RetrotechEmporium.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RetrotechEmporium.Models.Product", b =>
                {
                    b.HasOne("RetrotechEmporium.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RetrotechEmporium.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
